plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'net.golbarg.engtoper'
    compileSdk 35

    defaultConfig {
        applicationId "net.golbarg.engtoper"
        minSdk 28
        targetSdk 35
        versionCode 5
        versionName "1.5"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        setProperty("archivesBaseName", "eng-to-per-$versionName")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.android.about.page
    implementation libs.mpandroidchart
    implementation libs.highlight
    implementation libs.glide
    implementation libs.play.services.ads
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}